### ISSUE TITLE
Filter out selected countries from search suggestions

### ISSUE THREAD

**Issue by ikuisma** [ikuisma/carbfoot-swalab#21]
![image](https://user-images.githubusercontent.com/21037154/53736425-66104380-3e92-11e9-8573-a3baf216c367.png)

**Comment by esakemp** [comment]
![fix](https://user-images.githubusercontent.com/40692959/54195019-4dbdab80-44c6-11e9-99ed-5ebe41a4a1e4.png)

fixed
